// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL
{
    public partial class Customers
    {
        public string FullName { get; set; }
        public DateTime BirthDate { get; set; }
        public string IdNum { get; set; }
    }
}